name: alostora
description: "Alostora Admin Panel."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Architecture
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  go_router: ^17.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.12.0
  intl: ^0.20.2

  # Network
  dio: ^5.9.0

  # Storage
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

flutter:
  uses-material-design: true

  # This line enables the intl tool
  generate: true

  assets:
    - assets/images/
    - assets/images/logo/
